config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs do
    resources :blogcomments
  end
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :blogcomments, dependent: :destroy
end

app/models/blogcomment.rb
class Blogcomment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  has_rich_text :body
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :blogs, dependent: :destroy
         has_many :blogcomments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end
end

app/controllers/blogcomments_controller.rb
class BlogcommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_blog

    def create
        @comment = @blog.blogcomments.create(comment_params)
        @comment.user = current_user

        if @comment.save
            CommentMailer.with(user: current_user, comment: @comment, blog: @blog).comment_created.deliver_later
            flash[:notice] = "Comment has been created"
            redirect_to blog_path(@blog)
        else
            flash[:alert] = "Comment has not been created"
            redirect_to blog_path(@blog)
        end
    end

    def destroy
        @comment = @blog.blogcomments.find(params[:id]) 
        @comment.destroy
        redirect_to blog_path(@blog)
    end

    private

    def set_blog
        @blog = Blog.find(params[:blog_id])
    end

    def comment_params
        params.require(:blogcomment).permit(:body)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @comments = @blog.blogcomments.order(created_at: :desc)
  end

  # GET /blogs/new
  def new
    #@blog = Blog.new
    @blog = current_user.blogs.build
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    # @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @blog = current_user.blogs.find_by(id: params[:id])
    redirect_to blogs_path, notice: "You are not authorized." if @blog.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :user_id, :username, :email)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_blog

    def create
        @comment = @blog.comments.create(comment_params)
        @comment.user = current_user

        if @comment.save
            flash[:notice] = "Comment has been created"
            redirect_to blog_path(@blog)
        else
            flash[:alert] = "Comment has not been created"
            redirect_to blog_path(@blog)
        end
    end

    def destroy
        @comment = @blog.comments.find(params[:id]) 
        @comment.destroy
        redirect_to blog_path(@blog)
    end

    private

    def set_blog
        @blog = Blog.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogcomments_helper.rb
module BlogcommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogcomments/_comment.html.erb
<div class="comment-<%= comment.id %> container" style="border: 1px solid black; padding: 1em; margin: 1em;">
    <%= comment.user.name %><br>
    <span>Commented <%= time_ago_in_words(comment.created_at) %> ago</span>
    <% if current_user == comment.user %>
        <div class="button-group float-end">
            <%= button_to "Delete", [blog, comment], class:"btn btn-danger", method: :delete%>
        </div>
    <% end %>
    <hr>
    <%= comment.body%>

</div>

app/views/blogcomments/_form.html.erb
<%= form_with(model: [blog, blog.blogcomments.build]) do |f| %>
    <div class="form-control">
        <%= f.rich_text_area :body %>
        <%= f.submit "Reply", class: "btn btn-primary mt-1"%>
    </div>
<% end %>

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Name:</strong>
    <%= blog.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= blog.email %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= blog.content %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area:content %>
  </div>

  <div>
    <%= form.number_field:user_id, id: :blog_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.text_field:username, username: :blog_username, value: current_user.name, type: :hidden %>
  </div>

  <div>
    <%= form.text_field:email, email: :blog_email, value: current_user.email, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

<div class="container">
  <%= render 'blogcomments/form', blog: @blog %>
  <% @comments.each do |comment| %>
    <%= render 'blogcomments/comment', blog: @blog, comment: comment %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [blog, blog.comments.build]) do |f| %>
    <div class="form-control">
        <%= f.rich_text_area :body %>
        <%= f.submit "Reply", class: "btn btn-primary mt-1"%>
    </div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Blog App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Blogs', blogs_path, class: "nav-link" %>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Create Blog', new_blog_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Blog App</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br>
      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>